object_detection:
  label_map_path: workspace/data/custom01/label_map.pbtxt
  class_name_to_csv_header_mapping:
    Apple: Apples
    Banana: Banana
    Orange: Oranges
    Book: Textbooks
    Cerealbox: Cereal Boxes


  # the save model's performance is bad, don't know why. maybe due no preprossing?
  # we should use load from checkpoint first untile we solve this problem
  # load_model_from_checkpoint: false
  # model_dir: workspace/exported_models/efficientdet_d0_coco17_tpu/2021-10-24_v3/saved_model
  # min_score_thresh: 0.6

  # load_model_from_checkpoint: true
  # pipeline_config_path: workspace/exported_models/efficientdet_d0_coco17_tpu/2021-10-24_v3/pipeline.config
  # checkpoint_dir: workspace/exported_models/efficientdet_d0_coco17_tpu/2021-10-24_v3/checkpoint
  # checkpoint_no: 0
  # min_score_thresh: 0.6

  # best model
  load_model_from_checkpoint: true
  pipeline_config_path: workspace/exported_models/faster_rcnn_resnet50_v1_1024x1024/2021-10-29_v1/pipeline.config
  checkpoint_dir: workspace/exported_models/faster_rcnn_resnet50_v1_1024x1024/2021-10-29_v1/checkpoint
  checkpoint_no: 0
  min_score_thresh: 0.7
  detect_every_n_frame: 80
  post_processing:
    remove_too_small_bounding_box_min_area: 0.01
    remove_high_iou_bounding_boxes:
      min_iou_thresh: 0.85
      # when two scores are the same pick the class whos index is large 
      class_weight_order: 
        - Cerealbox
        - Book
        - Banana
        - Orange
        - Apple
    merge_bounding_box_for_one_class:
      # class_name merge_min_iou_thresh
      Banana: 0.2
      Orange: 0.7
      Cerealbox: 0.5
      Book: 0.5
      Apple: 0.9
    classifier_model_path: workspace/classifier/best1.h5
    use_classifer_for_classes:
      # class_name classifer_class_id
      Cerealbox: 1
      Book: 0