# load_model_from_checkpoint: false
# model_dir: workspace/exported_models/efficientdet_d0_coco17_tpu/v2/saved_model
# label_map_path: workspace/data/custom01/label_map.pbtxt

load_model_from_checkpoint: true
pipeline_config_path: workspace/exported_models/efficientdet_d0_coco17_tpu/v2/pipeline.config
checkpoint_dir: workspace/exported_models/efficientdet_d0_coco17_tpu/v2/checkpoint
checkpoint_no: 0
label_map_path: workspace/data/custom01/label_map.pbtxt
min_score_thresh: 0.6