object_detection:
  label_map_path: workspace/data/custom01/label_map.pbtxt

  # the save model's performance is bad, don't know why. maybe due no preprossing?
  # we should use load from checkpoint first untile we solve this problem
  # load_model_from_checkpoint: false
  # model_dir: workspace/exported_models/efficientdet_d0_coco17_tpu/2021-10-24_v3/saved_model
  # min_score_thresh: 0.6

  # load_model_from_checkpoint: true
  # pipeline_config_path: workspace/exported_models/efficientdet_d0_coco17_tpu/2021-10-24_v3/pipeline.config
  # checkpoint_dir: workspace/exported_models/efficientdet_d0_coco17_tpu/2021-10-24_v3/checkpoint
  # checkpoint_no: 0
  # min_score_thresh: 0.6

  load_model_from_checkpoint: true
  pipeline_config_path: workspace/models/faster_rcnn_resnet50_v1_1024x1024/2021-10-26_v1/pipeline.config
  checkpoint_dir: workspace/models/faster_rcnn_resnet50_v1_1024x1024/2021-10-26_v1
  checkpoint_no: 3
  min_score_thresh: 0.4
  detect_every_n_frame: 80